TEMA_VENTANA = "superhero"

FUENTE_TITULO = ("Impact", 18)
FUENTE_ETIQUETA = ("Arial Black", 11)
FUENTE_BOTON = ("Arial Black", 12)
FUENTE_RESULTADO = ("Arial Black", 11)

BOOTSTYLE_TITULO = "danger"
BOOTSTYLE_ETIQUETA = "secondary"
BOOTSTYLE_CALENDARIO = "danger"
BOOTSTYLE_BOTON = "danger"
BOOTSTYLE_EXITO = "success"
BOOTSTYLE_ADVERTENCIA = "warning"
BOOTSTYLE_ERROR = "danger"

VENTANA_ANCHO = 1200
VENTANA_ALTO = 480

PAD_X = 20
PAD_Y = 18
PAD_TITULO_Y = (25, 20)

TEXTO_TITULO = "SISTEMA DE CONTROL DE JUBILACIÓN"
TEXTO_ETIQUETA_FECHA = "Ingrese Fecha de Nacimiento:"
TEXTO_BOTON_CALCULAR = "CALCULAR"
TEXTO_INICIAL_RESULTADO = "Información: Para poder jubilarse debe tener 60 años o más."